# Generated by Django 5.2.4 on 2025-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0003_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
