# Generated by Django 5.2.4 on 2025-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0004_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
