# Generated by Django 5.2.4 on 2025-07-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0006_author_alter_book_slug_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                related_query_name="book",
                to="book_hub.author",
            ),
        ),
    ]
