# Generated by Django 5.2.4 on 2025-07-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0007_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("post_code", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_hub.address",
            ),
        ),
    ]
