# Generated by Django 5.2.4 on 2025-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0008_address_author_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="post_code",
            field=models.CharField(default="Unknown", max_length=15),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
