# Generated by Django 5.2.4 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_hub", "0009_alter_address_post_code_alter_address_street"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address Entries"},
        ),
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_hub.country"),
        ),
    ]
